### ISSUE TITLE
how to generate pkl files

### ISSUE THREAD

**Issue by frisk99** [CatOneTwo/OICR-PyTorch#13]
I'm a novice in this field.I want to train it on other datasets.How to generate selective search pkl files?
I try to find out the pkl files format but  get arrays full of 1. I only find the way to generate mat files  by matlabs.

**Comment by CatOneTwo** [comment]
I have got these pickle files from other projects directly so I cannot provide the scripts. I suggest you search for some selective search  Implementation for Python in GitHub.
